repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        # args: [--assume-in-merge]
        fail_fast: true
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
        # - id: check-yaml
        args: [--allow-multiple-documents]
      # - id: debug-statements
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: [--django]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
  # - repo: https://github.com/tox-dev/tox-ini-fmt
  #   rev: 1.3.1
  #   hooks:
  #     - id: tox-ini-fmt
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: 1.16.0
  #   hooks:
  #     - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  # - repo: https://github.com/psf/black
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  #     # - id: black-jupyter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--recursive, --quiet, --config, bandit.yaml]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8 # E***, W***, F***
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          # - flake8-variables-names # VNE***
          - mccabe # C9**
          - pep8-naming # N8**
